#!/bin/bash
sudo apt update
sudo apt install python-pip -y
sudo apt update



sudo apt install awscli -y

mkdir ~/.aws
echo '[default]' > ~/.aws/config
echo '[default]
aws_access_key_id = AKIAJQOLZFDJ6ODLUMLQ
aws_secret_access_key = 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' > ~/.aws/credentials






aws s3 sync s3://dyskala/cluster_case ${FOAM_RUN}/cluster_case

